<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, apellidos, direccion, telefono )>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (calle, poblacion, cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT telefono (tel_casa, tel_movil, tel_trabajo)>
<!ELEMENT tel_casa (#PCDATA)>
<!ELEMENT tel_movil (#PCDATA)>
<!ELEMENT tel_trabajo (#PCDATA)>
] >
<agenda>
  <contacto>
    <nombre>Juan</nombre>
    <apellidos>Pérez Pérez</apellidos>
    <direccion>
      <calle>El Pescador,1</calle>
      <poblacion>Tacoronte</poblacion>
      <cp>38350</cp>
    </direccion>
    <telefono>
      <tel_casa>922563295</tel_casa>
      <tel_movil>649035313</tel_movil>
      <tel_trabajo>922470000</tel_trabajo>
    </telefono>
  </contacto>
  <contacto>
    <nombre>María</nombre>
    <apellidos>Hernández Pérez</apellidos>
    <direccion>
      <calle>Andrómeda,1</calle>
      <poblacion>La Laguna</poblacion>
      <cp>38200</cp>
    </direccion>
    <telefono>
      <tel_casa>922111111</tel_casa>
      <tel_movil>649035377</tel_movil>
      <tel_trabajo>922470055</tel_trabajo>
    </telefono>
  </contacto>
</agenda>
  
